server:
    port: 8081

spring : 
    application : 
        name : fuples
    datasource:
        url: jdbc:sqlite:../fuples.db
        driver-class-name: org.sqlite.JDBC

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.community.dialect.SQLiteDialect

jwt:
    secret: Xl9VeVN5Zm01M3pwck1GbkBfI14jTWxjdlVmQGReNGpNLW1P

security:
    permitAll: # 토큰 없이 접근 허용
    authenticated: # 토큰만 있으면 접근 가능
    roles:
      signing_up: # 토큰 + SIGNING_UP 권한이 있어야 접근 가능
        - "/api/users/info"
      approved: # 그 외 모든 요청은 토큰 + APPROVED 권한이 있어야 접근 가능
        - "/**"
