server:
    port: ${SERVER_PORT:8081}

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:../fuples.db}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.sqlite.JDBC}
        hikari:
            connection-init-sql: |
                PRAGMA foreign_keys=ON;
                PRAGMA journal_mode=WAL;
                PRAGMA synchronous=NORMAL;

    jpa:
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
        show-sql: ${SPRING_JPA_SHOW_SQL:true}
        properties:
            hibernate:
                dialect: ${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.community.dialect.SQLiteDialect}

jwt:
    secret: ${JWT_SECRET:Xl9VeVN5Zm01M3pwck1GbkBfI14jTWxjdlVmQGReNGpNLW1P}

security:
    permitAll:
        - "/swagger-ui/**"
        - "/v3/api-docs/**"
        - "/swagger-ui.html"
        - "/api/auth/**"
    authenticated:
        - "/api/users/**"

springdoc:
    swagger-ui:
        operations-sorter: method
        tags-sorter: alpha

logging:
    level:
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE