server:
    port: 8081

spring : 
    application : 
        name : fuples
    datasource:
        url: jdbc:sqlite:./fuples.db
        driver-class-name: org.sqlite.JDBC

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.community.dialect.SQLiteDialect
