server:
    port: 8081

spring : 
    application : 
        name : fuples
    datasource:
        url: jdbc:sqlite:../fuples.db
        driver-class-name: org.sqlite.JDBC
        hikari:
            connection-init-sql: |
                PRAGMA foreign_keys=ON;
                PRAGMA journal_mode=WAL;
                PRAGMA synchronous=NORMAL;

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.community.dialect.SQLiteDialect

jwt:
    secret: Xl9VeVN5Zm01M3pwck1GbkBfI14jTWxjdlVmQGReNGpNLW1P

security:
    permitAll: # 토큰 없이 접근 허용
        - "/swagger-ui/**"
        - "/v3/api-docs/**"
        - "/swagger-ui.html"
        - "/api/auth/**"
    authenticated:
        - "/api/users"

springdoc:
    swagger-ui:
        operations-sorter: method
        tags-sorter: alpha
